--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 17/09/2018 17:49:50
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS fábricachocolates;

CREATE DATABASE fábricachocolates
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE fábricachocolates;

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  codCliente int(7) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  CI int(7) NOT NULL,
  teléfono int(7) DEFAULT NULL,
  celular int(8) NOT NULL,
  dirección varchar(50) DEFAULT NULL,
  puntos int(5) NOT NULL,
  PRIMARY KEY (codCliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `categoría`
--
CREATE TABLE categoría (
  codCategoría int(7) NOT NULL AUTO_INCREMENT,
  nombre varchar(30) NOT NULL,
  descripción varchar(255) DEFAULT NULL,
  PRIMARY KEY (codCategoría)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `producto`
--
CREATE TABLE producto (
  codProducto int(7) NOT NULL AUTO_INCREMENT,
  nombre varchar(30) NOT NULL,
  descripción varchar(50) DEFAULT NULL,
  precio decimal(5, 2) NOT NULL,
  codCategoría int(7) NOT NULL,
  PRIMARY KEY (codProducto)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE producto
ADD CONSTRAINT FK_producto_categoría_codCategoría FOREIGN KEY (codCategoría)
REFERENCES categoría (codCategoría) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `empleado`
--
CREATE TABLE empleado (
  codEmpleado int(7) NOT NULL AUTO_INCREMENT,
  nombre varchar(30) NOT NULL,
  CI int(7) NOT NULL,
  teléfono int(7) DEFAULT NULL,
  celular int(8) NOT NULL,
  dirección varchar(50) DEFAULT NULL,
  cargo varchar(30) NOT NULL,
  PRIMARY KEY (codEmpleado)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `venta`
--
CREATE TABLE venta (
  numVenta int(11) NOT NULL AUTO_INCREMENT,
  fecha datetime NOT NULL,
  codCliente int(7) NOT NULL,
  codEmpleado int(7) NOT NULL,
  PRIMARY KEY (numVenta)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE venta
ADD CONSTRAINT FK_venta_cliente_codCliente FOREIGN KEY (codCliente)
REFERENCES cliente (codCliente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE venta
ADD CONSTRAINT FK_venta_empleado_codEmpleado FOREIGN KEY (codEmpleado)
REFERENCES empleado (codEmpleado) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `factura`
--
CREATE TABLE factura (
  numVenta int(11) NOT NULL,
  NIT int(11) NOT NULL,
  nombre varchar(30) NOT NULL,
  descripción varchar(255) DEFAULT NULL,
  PRIMARY KEY (numVenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE factura
ADD CONSTRAINT FK_factura_venta_numVenta FOREIGN KEY (numVenta)
REFERENCES venta (numVenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `envío`
--
CREATE TABLE envío (
  codEnvío int(11) NOT NULL AUTO_INCREMENT,
  destinatario varchar(30) NOT NULL,
  teléfono int(8) NOT NULL,
  costoAdicional int(5) NOT NULL,
  numVenta int(11) NOT NULL,
  PRIMARY KEY (codEnvío)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE envío
ADD CONSTRAINT FK_envío_venta_numVenta FOREIGN KEY (numVenta)
REFERENCES venta (numVenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detalleventa`
--
CREATE TABLE detalleventa (
  codDetalle int(11) NOT NULL AUTO_INCREMENT,
  codProducto int(7) NOT NULL,
  cantidad int(5) NOT NULL,
  totalVenta decimal(10, 3) NOT NULL,
  numVenta int(11) NOT NULL,
  PRIMARY KEY (codDetalle)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_producto_codProducto FOREIGN KEY (codProducto)
REFERENCES producto (codProducto) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_venta_numVenta FOREIGN KEY (numVenta)
REFERENCES venta (numVenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `compraingrediente`
--
CREATE TABLE compraingrediente (
  codCompraIng int(11) NOT NULL AUTO_INCREMENT,
  proveedor varchar(30) NOT NULL,
  codEmpleado int(7) NOT NULL,
  nombre varchar(30) NOT NULL,
  PRIMARY KEY (codCompraIng)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE compraingrediente
ADD CONSTRAINT FK_compraingrediente_empleado_codEmpleado FOREIGN KEY (codEmpleado)
REFERENCES empleado (codEmpleado) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `ingredientes`
--
CREATE TABLE ingredientes (
  codIngrediente int(7) NOT NULL AUTO_INCREMENT,
  descripción varchar(50) DEFAULT NULL,
  costo decimal(5, 2) NOT NULL,
  numAlmacén int(3) NOT NULL,
  cantidad int(11) NOT NULL,
  PRIMARY KEY (codIngrediente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `ingredientesproducto`
--
CREATE TABLE ingredientesproducto (
  codProducto int(7) NOT NULL,
  codIngrediente int(11) NOT NULL,
  PRIMARY KEY (codProducto, codIngrediente)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE ingredientesproducto
ADD CONSTRAINT FK_ingredientesproducto_ingredientes_codIngrediente FOREIGN KEY (codIngrediente)
REFERENCES ingredientes (codIngrediente) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE ingredientesproducto
ADD CONSTRAINT FK_ingredientesproducto_producto_codProducto FOREIGN KEY (codProducto)
REFERENCES producto (codProducto) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detallecompraingredientes`
--
CREATE TABLE detallecompraingredientes (
  codIngrediente int(7) NOT NULL,
  codCompraIng int(11) NOT NULL,
  cantidad int(11) NOT NULL,
  totalCompra decimal(10, 3) NOT NULL,
  codDetalle int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (codDetalle)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detallecompraingredientes
ADD CONSTRAINT FK_detallecompraingredientes_compraingrediente_codCompraIng FOREIGN KEY (codCompraIng)
REFERENCES compraingrediente (codCompraIng) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detallecompraingredientes
ADD CONSTRAINT FK_detallecompraingredientes_ingredientes_codIngrediente FOREIGN KEY (codIngrediente)
REFERENCES ingredientes (codIngrediente) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table cliente
--
INSERT INTO cliente VALUES
(1, 'brami', 345, 987, 98, 'sacaba', 130);

-- 
-- Dumping data for table categoría
--
INSERT INTO categoría VALUES
(1, 'egvervr', 'erfre'),
(2, 'dwx', 'wex');

-- 
-- Dumping data for table empleado
--
INSERT INTO empleado VALUES
(1, 'aldo', 456, 987, 12345678, 'pacata', 'administrativo'),
(2, 'wew', 243, 43, 42, 'fcrf', 'rffe'),
(3, 'evsb', 352, 4365, 452, 'rvwsvrw', 'rwrr'),
(4, 'ererv', 42, 425, 425, 'rver', 'rcerv');

-- 
-- Dumping data for table venta
--
INSERT INTO venta VALUES
(2, '2309-01-23 00:00:00', 1, 1);

-- 
-- Dumping data for table producto
--
INSERT INTO producto VALUES
(2, 'wecec', 'wecew', 34.00, 1);

-- 
-- Dumping data for table ingredientes
--
INSERT INTO ingredientes VALUES
(1, 'rcw', 12.00, 1, 1);

-- 
-- Dumping data for table compraingrediente
--
INSERT INTO compraingrediente VALUES
(1, 's', 1, 's');

-- 
-- Dumping data for table ingredientesproducto
--
-- Table fábricachocolates.ingredientesproducto does not contain any data (it is empty)

-- 
-- Dumping data for table factura
--
-- Table fábricachocolates.factura does not contain any data (it is empty)

-- 
-- Dumping data for table envío
--
INSERT INTO envío VALUES
(3, 'r', 3, 3, 2);

-- 
-- Dumping data for table detalleventa
--
-- Table fábricachocolates.detalleventa does not contain any data (it is empty)

-- 
-- Dumping data for table detallecompraingredientes
--
-- Table fábricachocolates.detallecompraingredientes does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;